# Generated by Django 4.2.30 on 2026-05-10 08:05

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('marks1', models.IntegerField()),
                ('marks2', models.IntegerField()),
                ('marks3', models.IntegerField()),
                ('marks4', models.IntegerField()),
                ('total', models.IntegerField()),
                ('total_avg', models.FloatField()),
                ('Grade', models.CharField(max_length=100)),
            ],
        ),
    ]
